



import 'package:json_annotation/json_annotation.dart';

part 'country.g.dart'; // This will be generated by running the build_runner

@JsonSerializable()
class CountryModel {
  @JsonKey(name: 'Id')
  final int id;

  @JsonKey(name: 'country_name')
  final String country_name;

  @JsonKey(name: 'code')
  final String code;

  @JsonKey(name: 'show_hide')
  final String show_hide;



  CountryModel({
    required this.id,
    required this.country_name,
    required this.code,
    required this.show_hide,

  });

  factory CountryModel.fromJson(Map<String, dynamic> json) => _$CountryModelFromJson(json);

  Map<String, dynamic> toJson() => _$CountryModelToJson(this);
}

@JsonSerializable()
class Country {
  @JsonKey(name: 'success')
  final int success;

  @JsonKey(name: 'data')
  final List<Map<String , CountryModel>> data;

  Country({
    required this.success,
    required this.data,
  });

  factory Country.fromJson(Map<String, dynamic> json) =>
      _$CountryFromJson(json);

  Map<String, dynamic> toJson() => _$CountryToJson(this);
}
