
import 'package:json_annotation/json_annotation.dart';

part 'edu_degree.g.dart'; // This will be generated by running the build_runner

@JsonSerializable()
class EduDegree {

  @JsonKey(name: 'Id')
  final int id;

  @JsonKey(name: 'degree_name')
  final String degreeName;

  @JsonKey(name: 'degree_hindi')
  final String degreeHindi;

  @JsonKey(name: 'degree_guj')
  final String degreeGuj;

  @JsonKey(name: 'degree_marathi')
  final String degreeMarathi;

  @JsonKey(name: 'degree_tamil')
  final String degreeTamil;

  @JsonKey(name: 'degree_urdu')
  final String degreeUrdu;

  EduDegree({
    required this.id,
    required this.degreeName,
    required this.degreeHindi,
    required this.degreeGuj,
    required this.degreeMarathi,
    required this.degreeTamil,
    required this.degreeUrdu,
  });

  factory EduDegree.fromJson(Map<String, dynamic> json) => _$EduDegreeFromJson(json);

  Map<String, dynamic> toJson() => _$EduDegreeToJson(this);
}

@JsonSerializable()
class DegreesList {
  @JsonKey(name: 'success')
  final int success;

  @JsonKey(name: 'data')
  List<Map<String, EduDegree>> data;

  DegreesList({
    required this.success,
    required this.data,
  });


  factory DegreesList.fromJson(Map<String, dynamic> json) =>
      _$DegreesListFromJson(json);

  Map<String, dynamic> toJson() => _$DegreesListToJson(this);
}
