
import 'package:json_annotation/json_annotation.dart';

part 'institute_model.g.dart'; // This will be generated by running the build_runner

@JsonSerializable()
class InstituteModel {
  @JsonKey(name: 'Id')
  final int id;

  @JsonKey(name: 'institute_name')
  final String instituteName;

  @JsonKey(name: 'institute_hindi')
  final String instituteHindi;

  @JsonKey(name: 'institute_guj')
  final String instituteGuj;

  @JsonKey(name: 'institute_marathi')
  final String instituteMarathi;

  @JsonKey(name: 'institute_tamil')
  final String instituteTamil;

  @JsonKey(name: 'institute_urdu')
  final String instituteUrdu;

  InstituteModel({
    required this.id,
    required this.instituteName,
    required this.instituteHindi,
    required this.instituteGuj,
    required this.instituteMarathi,
    required this.instituteTamil,
    required this.instituteUrdu,
  });

  factory InstituteModel.fromJson(Map<String, dynamic> json) =>
      _$InstituteModelFromJson(json);

  Map<String, dynamic> toJson() => _$InstituteModelToJson(this);
}

@JsonSerializable()
class InstituteList {
  @JsonKey(name: 'success')
  final int success;

  @JsonKey(name: 'data')
  final List<Map<String, InstituteModel>> data;

  InstituteList({
    required this.success,
    required this.data,
  });

  factory InstituteList.fromJson(Map<String, dynamic> json) =>
      _$InstituteListFromJson(json);

  Map<String, dynamic> toJson() => _$InstituteListToJson(this);

}
