


import 'package:json_annotation/json_annotation.dart';

part 'login_response.g.dart'; // This will be generated by running the build_runner

@JsonSerializable()
class LoginResponse {
  @JsonKey(name: 'Id')
  final int id;


  final String name;
  final String surname;
  final String emailid;
  final String gender;

  @JsonKey(name: 'birthdate')
  final String birthdate;

  final String mobile;

  @JsonKey(name: 'profile_id')
  final String profileId;

  @JsonKey(name: 'user_verify')
  final String userVerify;

  @JsonKey(name: 'email_verify')
  final String emailVerify;

  @JsonKey(name: 'mobile_verify')
  final String mobileVerify;

  @JsonKey(name: 'community_id')
  final String communityId;

  @JsonKey(name: 'community_name')
  final String communityName;

  @JsonKey(name: 'delete_account')
  final String deleteAccount;

  @JsonKey(name: 'delete_account_reason')
  final String deleteAccountReason;

  @JsonKey(name: 'mobile_reg_token')
  final String mobileRegToken;

  @JsonKey(name: 'web_reg_token')
  final String webRegToken;

  @JsonKey(name: 'joined_date')
  final String joinedDate;

  LoginResponse({
    required this.id,
    required this.name,
    required this.surname,
    required this.emailid,
    required this.gender,
    required this.birthdate,
    required this.mobile,
    required this.profileId,
    required this.userVerify,
    required this.emailVerify,
    required this.mobileVerify,
    required this.communityId,
    required this.communityName,
    required this.deleteAccount,
    required this.deleteAccountReason,
    required this.mobileRegToken,
    required this.webRegToken,
    required this.joinedDate,
  });

  factory LoginResponse.fromJson(Map<String, dynamic> json) => _$LoginResponseFromJson(json);

  Map<String, dynamic> toJson() => _$LoginResponseToJson(this);
}
