

import 'package:json_annotation/json_annotation.dart';

part 'membership_model.g.dart'; // This will be generated by running the build_runner

@JsonSerializable()
class MembershipModel {
  @JsonKey(name: 'Id')
  final int id;

  @JsonKey(name: 'image')
  final String image;

  @JsonKey(name: 'plan_name')
  final String planName;

  @JsonKey(name: 'plan_price')
  final String planPrice;

  @JsonKey(name: 'details')
  final String details;

  @JsonKey(name: 'validity_days')
  final String validityDays;

  @JsonKey(name: 'profile_display')
  final String profileDisplay;

  @JsonKey(name: 'gallery_view')
  final String galleryView;

  @JsonKey(name: 'chatoption')
  final String chatOption;

  @JsonKey(name: 'express_interest')
  final String expressInterest;

  @JsonKey(name: 'number_express_interest')
  final String numberExpressInterest;

  @JsonKey(name: 'horoscopeview')
  final String horoscopeView;

  @JsonKey(name: 'pdf_access')
  final String pdfAccess;

  @JsonKey(name: 'num_pdf_access')
  final String numPdfAccess;

  @JsonKey(name: 'verified_phonenumbers')
  final String verifiedPhoneNumbers;

  @JsonKey(name: 'allowed_contacts')
  final String allowedContacts;

  @JsonKey(name: 'number_contacts')
  final String numberContacts;

  @JsonKey(name: 'number_horoscope')
  final String numberHoroscope;

  @JsonKey(name: 'number_chat')
  final String numberChat;

  @JsonKey(name: 'number_video')
  final String numberVideo;

  @JsonKey(name: 'verified_id_docs')
  final String verifiedIdDocs;

  @JsonKey(name: 'communityId')
  final String communityId;

  @JsonKey(name: 'ishidden')
  final String isHidden;

  MembershipModel({
    required this.id,
    required this.image,
    required this.planName,
    required this.planPrice,
    required this.details,
    required this.validityDays,
    required this.profileDisplay,
    required this.galleryView,
    required this.chatOption,
    required this.expressInterest,
    required this.numberExpressInterest,
    required this.horoscopeView,
    required this.pdfAccess,
    required this.numPdfAccess,
    required this.verifiedPhoneNumbers,
    required this.allowedContacts,
    required this.numberContacts,
    required this.numberHoroscope,
    required this.numberChat,
    required this.numberVideo,
    required this.verifiedIdDocs,
    required this.communityId,
    required this.isHidden,
  });

  factory MembershipModel.fromJson(Map<String, dynamic> json) =>
      _$MembershipModelFromJson(json);

  Map<String, dynamic> toJson() => _$MembershipModelToJson(this);
}

@JsonSerializable()
class MembershipOrder {
  @JsonKey(name: 'Id')
  final int? id;

  @JsonKey(name: 'member_name')
  final String? memberName;

  @JsonKey(name: 'package_name')
  final String? packageName;

  @JsonKey(name: 'payment_method')
  final String? paymentMethod;

  @JsonKey(name: 'amount')
  final String? amount;

  @JsonKey(name: 'status')
  final String? status;

  @JsonKey(name: 'code')
  final String? code;

  @JsonKey(name: 'date')
  final String? date;

  @JsonKey(name: 'isexpired')
  final String? isExpired;

  @JsonKey(name: 'userId')
  final String? userId;

  @JsonKey(name: 'communityId')
  final String? communityId;

  MembershipOrder({
     this.id,
     this.memberName,
     this.packageName,
     this.paymentMethod,
     this.amount,
     this.status,
     this.code,
     this.date,
     this.isExpired,
     this.userId,
     this.communityId,
  });

  factory MembershipOrder.fromJson(Map<String, dynamic> json) =>
      _$MembershipOrderFromJson(json);

  Map<String, dynamic> toJson() => _$MembershipOrderToJson(this);
}

@JsonSerializable()
class MembershipData {

  @JsonKey(name: 'success')
  final int success;

  @JsonKey(name: 'data')
  final List<List<Map<String, MembershipModel>>> data;

  MembershipData({
    required this.success,
    required this.data,
  });

  factory MembershipData.fromJson(Map<String, dynamic> json) =>
      _$MembershipDataFromJson(json);

  Map<String, dynamic> toJson() => _$MembershipDataToJson(this);
}
