
import 'package:json_annotation/json_annotation.dart';

part 'occupation.g.dart'; // This will be generated by running the build_runner

@JsonSerializable()
class Occupation {
  @JsonKey(name: 'Id')
  final int id;

  @JsonKey(name: 'occupation')
  final String occupationName;

  @JsonKey(name: 'occup_hindi')
  final String occupationHindi;

  @JsonKey(name: 'occup_guj')
  final String occupationGuj;

  @JsonKey(name: 'occup_marathi')
  final String occupationMarathi;

  @JsonKey(name: 'occup_tamil')
  final String occupationTamil;

  @JsonKey(name: 'occup_urdu')
  final String occupationUrdu;

  Occupation({
    required this.id,
    required this.occupationName,
    required this.occupationHindi,
    required this.occupationGuj,
    required this.occupationMarathi,
    required this.occupationTamil,
    required this.occupationUrdu,
  });

  factory Occupation.fromJson(Map<String, dynamic> json) =>
      _$OccupationFromJson(json);

  Map<String, dynamic> toJson() => _$OccupationToJson(this);
}

@JsonSerializable()
class OccupationData {
  @JsonKey(name: 'success')
  final int success;

  @JsonKey(name: 'data')
  final List<Map<String, Occupation>> data;

  OccupationData({
    required this.success,
    required this.data,
  });

  factory OccupationData.fromJson(Map<String, dynamic> json) =>
      _$OccupationDataFromJson(json);

  Map<String, dynamic> toJson() => _$OccupationDataToJson(this);
}
