

import 'package:json_annotation/json_annotation.dart';

part 'profile_details_model.g.dart'; // This will be generated by running the build_runner


@JsonSerializable()
class ProfileDetailsModel {

  final List<BasicInfo>? personalInfo;
  final List<ContactInfo>? contactInfo;
  final List<PhysicalInfo>? physicalInfo;
  final List<EducationInfo>? educationInfo;
  final List<OccupationInfo>? occupationInfo;
  final List<FamilyInfo>? familyInfo;
  final List<AstroInfo>? astroInfo;
  final List<PhotoInfo>? photoInfo;
  final List<PartnerPreferences>? partnerPreferences;
  final List<VerificationInfo>? verificationInfo;
  final List<PreferencesInfo>? preferencesInfo;
  final List<LikesInfo>? likesInfo;
  final List<BlockedUsersInfo>? blockedUsersInfo;
  final List<PrivacySettings>? privacySettings;

  ProfileDetailsModel({
     this.personalInfo,
     this.contactInfo,
     this.physicalInfo,
     this.educationInfo,
     this.occupationInfo,
     this.familyInfo,
     this.astroInfo,
     this.photoInfo,
     this.partnerPreferences,
     this.verificationInfo,
     this.preferencesInfo,
     this.likesInfo,
     this.blockedUsersInfo,
     this.privacySettings,
  });

  factory ProfileDetailsModel.fromJson(Map<String, dynamic> json) =>
      _$ProfileDetailsModelFromJson(json);

  Map<String, dynamic> toJson() => _$ProfileDetailsModelToJson(this);
}


@JsonSerializable()
class BasicInfo {
  @JsonKey(name: 'Id')
  final int? id;

  @JsonKey(name: 'fullname')
  final String? fullname;

  @JsonKey(name: 'created_by')
  final String? createdBy;

  final String? age;

  @JsonKey(name: 'marital_status')
  final String? maritalStatus;

  final String? caste;
  final String? subcaste;

  @JsonKey(name: 'language_known')
  final String? languageKnown;

  @JsonKey(name: 'mother_tongue')
  final String? motherTongue;

  BasicInfo({
     this.id,
     this.fullname,
     this.createdBy,
     this.age,
     this.maritalStatus,
     this.caste,
     this.subcaste,
     this.languageKnown,
     this.motherTongue,
  });

  factory BasicInfo.fromJson(Map<String, dynamic> json) => _$BasicInfoFromJson(json);

  Map<String, dynamic> toJson() => _$BasicInfoToJson(this);
}

@JsonSerializable()
class ContactInfo {
  @JsonKey(name: 'mobile_number')
  final String? mobileNumber;

  @JsonKey(name: 'whatsapp_number')
  final String? whatsappNumber;

  @JsonKey(name: 'permanent_adddress')
  final String? permanentAddress;

  final String? emailid;

  @JsonKey(name: 'alternate_mobile')
  final String? alternateMobile;

  @JsonKey(name: 'alternate_email')
  final String? alternateEmail;

  @JsonKey(name: 'working_address')
  final String? workingAddress;

  @JsonKey(name: 'contact_time')
  final String? contactTime;

  @JsonKey(name: 'perm_country')
  final String? permCountry;

  @JsonKey(name: 'perm_state')
  final String? permState;

  @JsonKey(name: 'perm_city')
  final String? permCity;

  @JsonKey(name: 'work_country')
  final String? workCountry;

  @JsonKey(name: 'work_state')
  final String? workState;

  @JsonKey(name: 'work_city')
  final String? workCity;

  ContactInfo({
     this.mobileNumber,
     this.whatsappNumber,
     this.permanentAddress,
     this.emailid,
     this.alternateMobile,
     this.alternateEmail,
     this.workingAddress,
     this.contactTime,
     this.permCountry,
     this.permState,
     this.permCity,
     this.workCountry,
     this.workState,
     this.workCity,
  });

  factory ContactInfo.fromJson(Map<String, dynamic> json) => _$ContactInfoFromJson(json);

  Map<String, dynamic> toJson() => _$ContactInfoToJson(this);
}

@JsonSerializable()
class PhysicalInfo {
  final String? weight;
  final String? height;

  final String? skintone;

  @JsonKey(name: 'blood_group')
  final String? bloodGroup;

  final String? fitness;

  @JsonKey(name: 'body_type')
  final String? bodyType;

  @JsonKey(name: 'is_handicap')
  final String? isHandicap;

  @JsonKey(name: 'handicap_detail')
  final String? handicapDetail;

  @JsonKey(name: 'diet_type')
  final String? dietType;

  @JsonKey(name: 'drink_type')
  final String? drinkType;

  @JsonKey(name: 'smoke_type')
  final String? smokeType;

  PhysicalInfo({
     this.weight,
     this.height,
     this.skintone,
     this.bloodGroup,
     this.fitness,
     this.bodyType,
     this.isHandicap,
     this.handicapDetail,
     this.dietType,
     this.drinkType,
     this.smokeType,
  });

  factory PhysicalInfo.fromJson(Map<String, dynamic> json) => _$PhysicalInfoFromJson(json);

  Map<String, dynamic> toJson() => _$PhysicalInfoToJson(this);
}

@JsonSerializable()
class EducationInfo {
  @JsonKey(name: 'is_from_admin_service')
  final String? isFromAdminService;

  @JsonKey(name: 'admin_position_name')
  final String? adminPositionName;

  @JsonKey(name: 'is_from_iit_iim_nit')
  final String? isFromIITIIMNIT;

  @JsonKey(name: 'institute_name')
  final String? instituteName;

  final String? education;

  @JsonKey(name: 'education_detail')
  final String? educationDetail;

  EducationInfo({
     this.isFromAdminService,
     this.adminPositionName,
     this.isFromIITIIMNIT,
     this.instituteName,
     this.education,
     this.educationDetail,
  });

  factory EducationInfo.fromJson(Map<String, dynamic> json) => _$EducationInfoFromJson(json);

  Map<String, dynamic> toJson() => _$EducationInfoToJson(this);
}

@JsonSerializable()
class OccupationInfo {
  final String? occupation;

  @JsonKey(name: 'occupation_detail')
  final String? occupationDetail;

  @JsonKey(name: 'annual_income')
  final String? annualIncome;

  @JsonKey(name: 'employment_type')
  final String? employmentType;

  @JsonKey(name: 'office_address')
  final String? officeAddress;

  OccupationInfo({
     this.occupation,
     this.occupationDetail,
     this.annualIncome,
     this.employmentType,
     this.officeAddress,
  });

  factory OccupationInfo.fromJson(Map<String, dynamic> json) => _$OccupationInfoFromJson(json);

  Map<String, dynamic> toJson() => _$OccupationInfoToJson(this);
}

@JsonSerializable()
class FamilyInfo {
  @JsonKey(name: 'family_status')
  final String? familyStatus;

  @JsonKey(name: 'family_type')
  final String? familyType;

  @JsonKey(name: 'family_value')
  final String? familyValue;

  @JsonKey(name: 'no_brother')
  final String? noBrother;

  @JsonKey(name: 'no_sister')
  final String? noSister;

  @JsonKey(name: 'married_brother')
  final String? marriedBrother;

  @JsonKey(name: 'married_sister')
  final String? marriedSister;

  @JsonKey(name: 'father_name')
  final String? fatherName;

  @JsonKey(name: 'mother_name')
  final String? motherName;

  @JsonKey(name: 'father_occupation')
  final String? fatherOccupation;

  @JsonKey(name: 'mother_occupation')
  final String? motherOccupation;

  @JsonKey(name: 'house_owned')
  final String? houseOwned;

  @JsonKey(name: 'house_type')
  final String? houseType;

  @JsonKey(name: 'parents_stay_options')
  final String? parentsStayOptions;

  @JsonKey(name: 'detail_family')
  final String? detailFamily;

  FamilyInfo({
     this.familyStatus,
     this.familyType,
     this.familyValue,
     this.noBrother,
     this.noSister,
     this.marriedBrother,
     this.marriedSister,
     this.fatherName,
     this.motherName,
     this.fatherOccupation,
     this.motherOccupation,
     this.houseOwned,
     this.houseType,
     this.parentsStayOptions,
     this.detailFamily,
  });

  factory FamilyInfo.fromJson(Map<String, dynamic> json) => _$FamilyInfoFromJson(json);

  Map<String, dynamic> toJson() => _$FamilyInfoToJson(this);
}

@JsonSerializable()
class AstroInfo {
  @JsonKey(name: 'astro_rashi')
  final String? astroRashi;

  @JsonKey(name: 'birth_star')
  final String? birthStar;

  final String? gotra;

  @JsonKey(name: 'believe_horoscope')
  final String? believeHoroscope;

  @JsonKey(name: 'birth_date')
  final String? birthDate;

  @JsonKey(name: 'birth_place')
  final String? birthPlace;

  @JsonKey(name: 'birth_time')
  final String? birthTime;

  @JsonKey(name: 'birth_country')
  final String? birthCountry;

  @JsonKey(name: 'horoscope_doc')
  final String? horoscopeDoc;

  @JsonKey(name: 'birth_location')
  final String? birthLocation;

  final String? timezone;

  @JsonKey(name: 'is_mangalik')
  final String? isMangalik;

  AstroInfo({
     this.astroRashi,
     this.birthStar,
     this.gotra,
     this.believeHoroscope,
     this.birthDate,
     this.birthPlace,
     this.birthTime,
     this.birthCountry,
     this.horoscopeDoc,
     this.birthLocation,
     this.timezone,
     this.isMangalik,
  });

  factory AstroInfo.fromJson(Map<String , dynamic> json) => _$AstroInfoFromJson(json);

  Map<String, dynamic> toJson() => _$AstroInfoToJson(this);
}

@JsonSerializable()
class PhotoInfo {
  @JsonKey(name: 'Id')
  final int? id;

  final String? pic1;
  final String? pic2;
  final String? pic3;
  final String? pic4;
  final String? pic5;
  final String? pic6;
  final String? pic7;
  final String? pic8;

  @JsonKey(name: 'isverifypic1')
  final String? isVerifyPic1;

  @JsonKey(name: 'isverifypic2')
  final String? isVerifyPic2;

  @JsonKey(name: 'isverifypic3')
  final String? isVerifyPic3;

  @JsonKey(name: 'isverifypic4')
  final String? isVerifyPic4;

  @JsonKey(name: 'isverifypic5')
  final String? isVerifyPic5;

  @JsonKey(name: 'isverifypic6')
  final String? isVerifyPic6;

  @JsonKey(name: 'isverifypic7')
  final String? isVerifyPic7;

  @JsonKey(name: 'isverifypic8')
  final String? isVerifyPic8;

  @JsonKey(name: 'isverifypic9')
  final String? isVerifyPic9;

  @JsonKey(name: 'isverifypic10')
  final String? isVerifyPic10;

  @JsonKey(name: 'userId')
  final String? userId;

  @JsonKey(name: 'communityId')
  final String? communityId;

  @JsonKey(name: 'profileId')
  final String? profileId;

  PhotoInfo({
     this.id,
     this.pic1,
      this.pic2,
     this.pic3,
     this.pic4,
      this.pic5,
     this.pic6,
     this.pic7,
      this.pic8,
     this.isVerifyPic1,
     this.isVerifyPic2,
     this.isVerifyPic3,
     this.isVerifyPic4,
     this.isVerifyPic5,
     this.isVerifyPic6,
     this.isVerifyPic7,
     this.isVerifyPic8,
     this.isVerifyPic9,
     this.isVerifyPic10,
     this.userId,
     this.communityId,
     this.profileId,
  });

  factory PhotoInfo.fromJson(Map<String, dynamic> json) => _$PhotoInfoFromJson(json);

  Map<String, dynamic> toJson() => _$PhotoInfoToJson(this);
}

@JsonSerializable()
class PartnerPreferences {
  @JsonKey(name: 'age_range')
  final String? ageRange;

  @JsonKey(name: 'height_range')
  final String? heightRange;

  @JsonKey(name: 'marital_status')
  final String? maritalStatus;

  final String? caste;
  final String? subcaste;
  final String? skintone;

  final String? state;
  final String? city;

  @JsonKey(name: 'education_list')
  final String? educationList;

  final String? occupation;

  @JsonKey(name: 'family_value')
  final String? familyValue;

  @JsonKey(name: 'diet_type')
  final String? dietType;

  @JsonKey(name: 'body_type')
  final String? bodyType;

  @JsonKey(name: 'drink_type')
  final String? drinkType;

  @JsonKey(name: 'smoke_type')
  final String? smokeType;

  @JsonKey(name: 'annual_income')
  final String? annualIncome;

  @JsonKey(name: 'partner_details')
  final String? partnerDetails;

  PartnerPreferences({
     this.ageRange,
     this.heightRange,
     this.maritalStatus,
     this.caste,
     this.subcaste,
     this.skintone,
     this.state,
     this.city,
     this.educationList,
     this.occupation,
     this.familyValue,
     this.dietType,
     this.bodyType,
     this.drinkType,
     this.smokeType,
     this.annualIncome,
     this.partnerDetails,
  });

  factory PartnerPreferences.fromJson(Map<String, dynamic> json) => _$PartnerPreferencesFromJson(json);

  Map<String, dynamic> toJson() => _$PartnerPreferencesToJson(this);
}

@JsonSerializable()
class VerificationInfo {
  @JsonKey(name: 'Id')
  final String? id;

  @JsonKey(name: 'id_proofs')
  final String? idProofs;

  @JsonKey(name: 'education_proof')
  final String? educationProof;

  @JsonKey(name: 'income_proof')
  final String? incomeProof;

  @JsonKey(name: 'is_id_verify')
  final String? isIdVerify;

  @JsonKey(name: 'is_education_verify')
  final String? isEducationVerify;

  @JsonKey(name: 'is_income_verify')
  final String? isIncomeVerify;

  @JsonKey(name: 'userId')
  final String? userId;

  @JsonKey(name: 'communityId')
  final String? communityId;

  @JsonKey(name: 'profileId')
  final String? profileId;

  @JsonKey(name: 'user_verify')
  final String? userVerify;

  @JsonKey(name: 'email_verify')
   String? emailVerify;

  @JsonKey(name: 'mobile_verify')
   String? mobileVerify;



  VerificationInfo({
     this.id,
     this.idProofs,
     this.educationProof,
     this.incomeProof,
     this.isIdVerify,
     this.isEducationVerify,
     this.isIncomeVerify,
     this.userId,
     this.communityId,
     this.profileId,
     this.userVerify,
     this.emailVerify,
     this.mobileVerify,
  });

  factory VerificationInfo.fromJson(Map<String, dynamic> json) => _$VerificationInfoFromJson(json);

  Map<String, dynamic> toJson() => _$VerificationInfoToJson(this);
}

@JsonSerializable()
class PreferencesInfo {
  @JsonKey(name: 'shortlist')
  final String? shortlist;

  PreferencesInfo({
     this.shortlist,
  });

  factory PreferencesInfo.fromJson(Map<String, dynamic> json) => _$PreferencesInfoFromJson(json);

  Map<String, dynamic> toJson() => _$PreferencesInfoToJson(this);
}

@JsonSerializable()
class LikesInfo {
  final String? likes;

  LikesInfo({
     this.likes,
  });

  factory LikesInfo.fromJson(Map<String, dynamic> json) => _$LikesInfoFromJson(json);

  Map<String, dynamic> toJson() => _$LikesInfoToJson(this);
}

@JsonSerializable()
class BlockedUsersInfo {
  @JsonKey(name: 'blocked_users')
  final String? blockedUsers;

  BlockedUsersInfo({
     this.blockedUsers,
  });

  factory BlockedUsersInfo.fromJson(Map<String, dynamic> json) => _$BlockedUsersInfoFromJson(json);

  Map<String, dynamic> toJson() => _$BlockedUsersInfoToJson(this);
}

@JsonSerializable()
class PrivacySettings {
  @JsonKey(name: 'Id')
  final int? id;

  @JsonKey(name: 'phone_privacy')
  final String? phonePrivacy;

  @JsonKey(name: 'photo_privacy')
  final String? photoPrivacy;

  @JsonKey(name: 'horoscope_privacy')
  final String? horoscopePrivacy;

  @JsonKey(name: 'userId')
  final String? userId;

  @JsonKey(name: 'communityId')
  final String? communityId;

  @JsonKey(name: 'profileId')
  final String? profileId;

  @JsonKey(name: 'user_verify')
  final String? user_verify;

  @JsonKey(name: 'email_verify')
  final String? email_verify;

  @JsonKey(name: 'mobile_verify')
  final String? mobile_verify;

  PrivacySettings({
     this.id,
      this.phonePrivacy,
      this.photoPrivacy,
       this.horoscopePrivacy,
       this.userId,
       this.communityId,
       this.profileId,
       this.user_verify,
        this.mobile_verify,
       this.email_verify
  });

  factory PrivacySettings.fromJson(Map<String, dynamic> json) => _$PrivacySettingsFromJson(json);

  Map<String, dynamic> toJson() => _$PrivacySettingsToJson(this);

}
