



import 'package:json_annotation/json_annotation.dart';

part 'state_model.g.dart'; // This will be generated by running the build_runner

@JsonSerializable()
class StateModel {
  @JsonKey(name: 'Id')
  final int id;

  @JsonKey(name: 'state_name')
  final String stateName;

  @JsonKey(name: 'state_hindi')
  final String stateHindi;

  @JsonKey(name: 'state_guj')
  final String stateGuj;

  @JsonKey(name: 'state_marathi')
  final String stateMarathi;

  @JsonKey(name: 'state_tamil')
  final String stateTamil;

  @JsonKey(name: 'state_urdu')
  final String stateUrdu;

  @JsonKey(name: 'country_id')
  final String countryId;

  StateModel({
    required this.id,
    required this.stateName,
    required this.stateHindi,
    required this.stateGuj,
    required this.stateMarathi,
    required this.stateTamil,
    required this.stateUrdu,
    required this.countryId,
  });

  factory StateModel.fromJson(Map<String, dynamic> json) => _$StateModelFromJson(json);

  Map<String, dynamic> toJson() => _$StateModelToJson(this);
}

@JsonSerializable()
class StateData {
  @JsonKey(name: 'success')
  final int success;

  @JsonKey(name: 'data')
  final List<Map<String, StateModel>> data;

  StateData({
    required this.success,
    required this.data,
  });

  factory StateData.fromJson(Map<String, dynamic> json) =>
      _$StateDataFromJson(json);

  Map<String, dynamic> toJson() => _$StateDataToJson(this);
}
