



import 'package:json_annotation/json_annotation.dart';

part 'subcaste_model.g.dart'; // This will be generated by running the build_runner

@JsonSerializable()
class SubcasteModel {
  @JsonKey(name: 'Id')
  final int id;

  final String subcaste;

  @JsonKey(name: 'casteId')
  final String casteId;

  @JsonKey(name: 'communityId')
  final String communityId;

  SubcasteModel({
    required this.id,
    required this.subcaste,
    required this.casteId,
    required this.communityId,
  });


  factory SubcasteModel.fromJson(Map<String, dynamic> json) =>
      _$SubcasteModelFromJson(json);

  Map<String, dynamic> toJson() => _$SubcasteModelToJson(this);

}

@JsonSerializable()
class SubcasteData {
  @JsonKey(name: 'success')
  final int success;

  @JsonKey(name: 'data')
  final List<Map<String, SubcasteModel>> data;

  SubcasteData({
    required this.success,
    required this.data,
  });

  factory SubcasteData.fromJson(Map<String, dynamic> json) =>
      _$SubcasteDataFromJson(json);

  Map<String, dynamic> toJson() => _$SubcasteDataToJson(this);
}
